
#define APB_CTRL_SYSCLK_CONF (DR_REG_APB_CTRL_BASE + 0x0)
#define APB_CTRL_CLK_EN (BIT(11))
#define APB_CTRL_CLK_EN_S 11
#define APB_CTRL_APB_CTRL_CLK_320M_EN (BIT(10))
#define APB_CTRL_APB_CTRL_CLK_320M_EN_S 10
#define APB_CTRL_APB_CTRL_PRE_DIV_CNT 0x000003FF
#define APB_CTRL_APB_CTRL_PRE_DIV_CNT_S 0

#define APB_CTRL_XTAL_TICK_CONF (DR_REG_APB_CTRL_BASE + 0x4)
#define APB_CTRL_APB_CTRL_XTAL_TICK_NUM 0x0000FFFF
#define APB_CTRL_APB_CTRL_XTAL_TICK_NUM_S 0

#define APB_CTRL_PLL_TICK_CONF (DR_REG_APB_CTRL_BASE + 0x8)
#define APB_CTRL_APB_CTRL_PLL_TICK_NUM 0x0000FFFF
#define APB_CTRL_APB_CTRL_PLL_TICK_NUM_S 0

#define APB_CTRL_CK12M_TICK_CONF (DR_REG_APB_CTRL_BASE + 0xC)
#define APB_CTRL_APB_CTRL_CK12M_TICK_NUM 0x0000FFFF
#define APB_CTRL_APB_CTRL_CK12M_TICK_NUM_S 0

#define APB_CTRL_DATE (DR_REG_APB_CTRL_BASE + 0x7C)
#define APB_CTRL_APB_CTRL_DATE 0xFFFFFFFF
#define APB_CTRL_APB_CTRL_DATE_S 0
#define APB_CTRL_APB_CTRL_DATE_VERSION 0x15052100
